"pull_request_title": "chore(localize): updated translation fron Crowdin"
"pull_request_labels": ["crowdin"]
"commit_message": "[skip ci]"

files:
  - source: /src/locales/e/*.json
    translation: /src/locales/%locale%/%original_file_name%
