name: New translation language for the Organized app
description: Request a new language to be added to Crowdin platform
title: '[Language] - New Language Request'
labels: [i18n]
body:
  - type: markdown
    attributes:
      value: |
        Add an issue title with this format: [Language] - New Language Request
  - type: textarea
    attributes:
      label: 'Enter the jw.org url to access this language:'
      placeholder: |
        https://www.jw.org
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        We can do an AI-based translation of the language, if you send us the list of translations in your language. Afterwards, you will be able to proofread text strings instead of translating everything from scratch.
  - type: textarea
    attributes:
      label: 'Congregation'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Assignment'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Publisher'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Meeting'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Midweek meeting'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Weekend meeting'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Circuit overseer'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Student (of a meeting)'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Assistant (of a student)'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Elder'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Ministerial servant'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Ministry'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Service'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Report'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Meeting Schedule'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Schedule'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Pioneer application'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Auxiliary pioneer'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Regular pioneer'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Speaker'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Talk'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Memorial'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Chairman'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Prayer'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Reader'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Meeting workbook'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Governing Body Update (video)'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Organizational Accomplishments (video)'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Branch office'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Bethel'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Territory'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Do you feel native to be a proofreader of the language? If yes, please provide your Crowdin username:'
      placeholder: |
        Yes, I can proofread the translations. My Crowdin username is...
    validations:
      required: false
