name: Translation for CPE app
description: Request a new language to be added to CPE app
labels: [i18n]
body:
  - type: markdown
    attributes:
      value: |
        Add an issue title with this format: Language - New Language Request