name: redeploy-dev

on:
  workflow_dispatch:

permissions: read-all

jobs:
  rebuild_deploy:
    name: Rebuild and Deploy to Development
    environment:
      name: Development
      url: https://dev-lmm-oa-sws.web.app
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout for firebase deployment
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: danielmillan/pipelines-firebase-hosting
          ref: '1.0.8'
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/pipelines-firebase-hosting

      - name: Checkout for release preparation
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: alpha
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package dependencies
        run: npm ci

      - name: Rebuild App
        run: npm run build

      - name: Check if new version has been generated
        id: check_build
        uses: andstor/file-existence-action@87d74d4732ddb824259d80c8a508c0124bf1c673
        with:
          files: 'build'

      - name: Deploy to Firebase
        if: ${{ steps.check_build.outputs.files_exists == 'true' }}
        uses: danielmillan/pipelines-firebase-hosting@8a7c15d150288fde37efe3edb186e5bb5931c3de
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          resources-name: build
          project-name: ${{ secrets.FIREBASE_PROJECT }}
